apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main
        image: fiber-prisma-main
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1Gi"
            cpu: "1m"
          limits:
            memory: "1Gi"
            cpu: "2m"
        ports:
        - containerPort: 3000
      - name: database-engine
        image: fiber-prisma-db-engine
        imagePullPolicy: Never
        env:
          - name: DATABASE_URL
            value: postgresql://saltyaom:482Ysd.rA8DhiZNaXRzgX@b_HCu!8qnY7C-wuFE*9Y8tDZCVr23Go2fW@35.247.173.198/prismaQueue?schema=queue
        resources:
          requests:
            memory: "1Gi"
            cpu: "1m"
          limits:
            memory: "2Gi"
            cpu: "2m"
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: NodePort
  selector:
    app: main-app
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  labels:
      name: main-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: main-service
            port:
              number: 80